version: '3'

services:
  postgres:
    image: postgres:latest
    container_name: meu-postgres
    environment:
      POSTGRES_DB: meu_banco
      POSTGRES_USER: meu_usuario
      POSTGRES_PASSWORD: minha_senha
    ports:
      - "5432:5432"
    volumes:
      - ./dados_postgres:/var/lib/postgresql/data

  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: meu-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: meu_email@example.com
      PGADMIN_DEFAULT_PASSWORD: minha_senha_pgadmin
    ports:
      - "5050:80"
    depends_on:
      - postgres