# Generated by Django 4.2.7 on 2023-12-04 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Projeto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(help_text='titulo do projeto', max_length=100, verbose_name='Titulo do projeto ')),
                ('descricao', models.CharField(help_text='descrição do projeto', max_length=100, verbose_name='Descrição de projeto')),
                ('tecnologia', models.CharField(help_text='Tecnologia do projeto', max_length=100, verbose_name='Tecnologia do projeto')),
            ],
            options={
                'verbose_name': 'projeto',
                'verbose_name_plural': 'projetos',
                'db_table': 'projeto',
            },
        ),
    ]
